"""The two synthetic samples offered on the /try front door must survive the
REAL pipeline, not a mock of it.

These are the files a stranger clicks "Try a sample" on. If a detection
signature or an adapter changes shape, the sample stops parsing and the front
door answers "we couldn't read that file" to the very people we invited. That
failure is invisible from the adapter's own unit tests -- they run against
fixtures, not against the committed PDFs -- so it is pinned here.

The samples are generated by `scripts/gen_preview_samples.py` and committed.
The last test re-runs the generator into a temporary directory and compares the
parse, so a script edited without regenerating the PDFs fails in CI rather than
leaving the two silently out of step.
"""

from decimal import Decimal
from pathlib import Path

import pytest

from usali.adaptors.pdf import extract_words_from_bytes
from usali.detect import detect_report_signature
from usali.server import _parse_preview_sync

REPO_ROOT = Path(__file__).resolve().parents[1]
SAMPLES = REPO_ROOT / "frontend" / "public" / "samples"

OPERA = SAMPLES / "opera-trial-balance-sample.pdf"
AUTOCLERK = SAMPLES / "autoclerk-transaction-summary-sample.pdf"


@pytest.mark.parametrize(
    ("path", "signature"),
    [(OPERA, ("OPERA", "trial_balance")), (AUTOCLERK, ("AUTOCLERK", "transaction_summary"))],
    ids=["opera", "autoclerk"],
)
def test_sample_is_detected_as_the_report_it_claims_to_be(path, signature):
    assert detect_report_signature(extract_words_from_bytes(path.read_bytes())) == signature


@pytest.mark.parametrize("path", [OPERA, AUTOCLERK], ids=["opera", "autoclerk"])
def test_sample_previews_ok_with_usable_lines(path):
    res = _parse_preview_sync(path.read_bytes())
    assert res["status"] == "ok", res
    payload = res["payload"]
    assert payload["business_date"] == "2026-06-21"
    # A sample that parses to two lines is technically "ok" and useless as a
    # demonstration; the page it sells is a P&L, so it has to look like one.
    assert len(payload["pnl_lines"]) >= 10
    assert {line["major"] for line in payload["pnl_lines"]} >= {
        "Operated Departments", "Settlements", "Taxes (Pass-Through)"
    }


def test_opera_sample_leaves_a_code_needing_review():
    """One code is deliberately unmapped (5210, Pet Fee). A sample where
    everything maps would advertise a coverage we do not have -- the honest
    picture is that a first look at a new property leaves a few codes to
    confirm, and the front-door copy says exactly that. If someone "fixes" this
    by adding 5210 to mapping/opera.yaml, this test says why not to."""
    payload = _parse_preview_sync(OPERA.read_bytes())["payload"]
    assert payload["codes_mapped"] < payload["codes_recognized"]
    assert payload["codes_needs_review"] > 0


def test_autoclerk_sample_ties_to_its_own_grand_total():
    """`parse_transaction_summary` REFUSES a report whose rows do not sum to its
    GRAND TOTAL rather than return an unverified parse. A hand-typed total that
    drifted a cent would turn this sample into an "unreadable file" on the front
    door, so the generator computes it -- and this asserts it stayed computed."""
    res = _parse_preview_sync(AUTOCLERK.read_bytes())
    # Reaching "ok" at all IS the tie holding — the adapter raises otherwise, and
    # the endpoint turns that into "unreadable".
    assert res["status"] == "ok", res
    lines = res["payload"]["pnl_lines"]
    assert sum(Decimal(line["amount"]) for line in lines) == Decimal("0.00")


@pytest.mark.parametrize("path", [OPERA, AUTOCLERK], ids=["opera", "autoclerk"])
def test_committed_sample_matches_what_the_generator_produces(path, tmp_path, monkeypatch):
    """The committed PDF and the script that claims to produce it must agree.
    Comparing bytes would fail on reportlab's embedded timestamp, so this
    compares the thing that actually matters: the payload each one previews to.
    """
    import scripts.gen_preview_samples as gen

    monkeypatch.setattr(gen, "OPERA_PDF", tmp_path / "opera.pdf")
    monkeypatch.setattr(gen, "AUTOCLERK_PDF", tmp_path / "autoclerk.pdf")
    gen.build_opera_pdf(gen.OPERA_PDF)
    gen.build_autoclerk_pdf(gen.AUTOCLERK_PDF)
    regenerated = gen.OPERA_PDF if path is OPERA else gen.AUTOCLERK_PDF
    assert _parse_preview_sync(regenerated.read_bytes()) == _parse_preview_sync(
        path.read_bytes()
    )
