// One-off generator for the cross-library HPKE interop fixture (Pillar C1).
//
// This is the CRUX of C1: it proves the browser crypto library (@hpke/core)
// seals a value that the server crypto library (pyhpke) can open — the exact
// production path (browser -> DB -> HSM). The generated fixture is committed and
// asserted from BOTH sides (tests/test_hpke_interop.py, src/lib/piiSeal.test.ts).
//
// The contract, identical on both sides and NON-NEGOTIABLE:
//   suite = DHKEM(P-256, HKDF-SHA256) + HKDF-SHA256 + AES-256-GCM
//   info  = UTF-8 "usali-payroll-pii/v1"
//   aad   = UTF-8 "7:ssn"  (i.e. "<employee_id>:<field>")
//   enc / recipient public key = SEC1 uncompressed point (65 bytes, 0x04 || X || Y)
//   envelope JSON = usali.pii_crypto.SealedEnvelope.to_json() shape
//
// The dev keypair below is FIXED (generated once with Python `cryptography`) so
// the fixture is reproducible: re-running this script re-seals with the same
// recipient key. HPKE is non-deterministic (fresh ephemeral per seal), so the
// enc/ct bytes change on each run, but any run produces a fixture both libraries
// agree on. This is a throwaway DEV key — never used in prod.
//
// Regenerate:  node frontend/scripts/gen_hpke_fixture.mjs
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  Aes256Gcm,
  CipherSuite,
  DhkemP256HkdfSha256,
  HkdfSha256,
} from '@hpke/core'

// Must match usali.pii_crypto.SUITE_LABEL exactly.
const SUITE_LABEL = 'DHKEM-P256-HKDF-SHA256/HKDF-SHA256/AES-256-GCM'
const INFO = 'usali-payroll-pii/v1'
const KEY_ID = 'interop'
const PLAINTEXT = '123-45-6789'
const AAD = '7:ssn'

// Fixed dev recipient key (P-256), three representations of the SAME key:
//   - PKCS8 DER (full)  -> Python's load_der_private_key (server open path)
//   - raw 32-byte scalar -> @hpke/core kem.importKey('raw', .., false) (JS open path)
//   - SEC1 uncompressed public point (65 bytes) -> sealing target
const PRIVATE_KEY_PKCS8_B64 =
  'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg5JyIBNNTfe6jwsGOIwSBa/17+lxiut3nSxlCEzn6kGOhRANCAAQOLLK5h++ev5oy9I7UNxHNzk/1ZBCOzUXv3BUOPtuZqc1W9eBC07MfdHnetwOOKZ9l3AK+Mjmz91b+v+cCvAQC'
const PRIVATE_KEY_RAW_B64 = '5JyIBNNTfe6jwsGOIwSBa/17+lxiut3nSxlCEzn6kGM='
const PUBLIC_KEY_SEC1_B64 =
  'BA4ssrmH756/mjL0jtQ3Ec3OT/VkEI7NRe/cFQ4+25mpzVb14ELTsx90ed63A44pn2XcAr4yObP3Vv6/5wK8BAI='

const b64ToBytes = (b64) => Uint8Array.from(Buffer.from(b64, 'base64'))
const bytesToB64 = (u8) => Buffer.from(u8).toString('base64')
const utf8 = (s) => new TextEncoder().encode(s)

const suite = new CipherSuite({
  kem: new DhkemP256HkdfSha256(),
  kdf: new HkdfSha256(),
  aead: new Aes256Gcm(),
})

// Import the recipient public key as a raw SEC1 uncompressed point (65 bytes) —
// the interop-safe wire format shared with pyhpke / `cryptography`.
const recipientPublicKey = await suite.kem.importKey(
  'raw',
  b64ToBytes(PUBLIC_KEY_SEC1_B64),
  true,
)

// Seal exactly as the browser client will: info binds the app context, aad binds
// employee_id:field. `sender.enc` is the HPKE encapsulated key (SEC1 point).
const sender = await suite.createSenderContext({
  recipientPublicKey,
  info: utf8(INFO),
})
const ct = await sender.seal(utf8(PLAINTEXT), utf8(AAD))
const encBytes = new Uint8Array(sender.enc)
const ctBytes = new Uint8Array(ct)

if (encBytes.byteLength !== 65) {
  throw new Error(`enc must be a 65-byte SEC1 point, got ${encBytes.byteLength}`)
}

// Self-check: the JS side must be able to open its own seal with the raw private
// scalar. If this throws, the fixture is not internally consistent — do not write.
const recipientKey = await suite.kem.importKey(
  'raw',
  b64ToBytes(PRIVATE_KEY_RAW_B64),
  false,
)
const recip = await suite.createRecipientContext({
  recipientKey,
  enc: sender.enc,
  info: utf8(INFO),
})
const roundTrip = new TextDecoder().decode(await recip.open(ct, utf8(AAD)))
if (roundTrip !== PLAINTEXT) {
  throw new Error(`self-check failed: opened "${roundTrip}" != "${PLAINTEXT}"`)
}

const fixture = {
  note: 'Generated by @hpke/core; pyhpke MUST open it. Regenerate with frontend/scripts/gen_hpke_fixture.mjs. Do not edit by hand.',
  private_key_pkcs8_b64: PRIVATE_KEY_PKCS8_B64,
  private_key_raw_b64: PRIVATE_KEY_RAW_B64,
  public_key_sec1_b64: PUBLIC_KEY_SEC1_B64,
  plaintext: PLAINTEXT,
  aad: AAD,
  info: INFO,
  envelope: {
    version: 1,
    suite: SUITE_LABEL,
    key_id: KEY_ID,
    enc: bytesToB64(encBytes),
    ct: bytesToB64(ctBytes),
  },
}

const here = dirname(fileURLToPath(import.meta.url))
const out = join(here, '..', '..', 'tests', 'fixtures', 'hpke_interop.json')
writeFileSync(out, JSON.stringify(fixture, null, 2) + '\n')
console.log(`wrote ${out}`)
console.log(`  enc ${encBytes.byteLength}B  ct ${ctBytes.byteLength}B  self-check OK`)
