"""targets forecast

Revision ID: 178480aede62
Revises: 27ff79238f7a
Create Date: 2026-07-17 21:56:55.397392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178480aede62'
down_revision: Union[str, Sequence[str], None] = '27ff79238f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupancy_forecast',
    sa.Column('forecast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('occupied_rooms', sa.Integer(), nullable=False),
    sa.Column('entered_by', sa.String(length=64), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.property_id'], ),
    sa.PrimaryKeyConstraint('forecast_id'),
    sa.UniqueConstraint('property_id', 'business_date')
    )
    op.create_table('labor_standard',
    sa.Column('standard_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('basis', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.property_id'], ),
    sa.PrimaryKeyConstraint('standard_id'),
    sa.UniqueConstraint('department_id')
    )
    op.add_column('employee', sa.Column('availability_note', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'availability_note')
    op.drop_table('labor_standard')
    op.drop_table('occupancy_forecast')
    # ### end Alembic commands ###
