"""pii vault

Revision ID: 41f376721261
Revises: a2d2d34af34e
Create Date: 2026-07-15 21:56:18.576655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f376721261'
down_revision: Union[str, Sequence[str], None] = 'a2d2d34af34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_schedule',
    sa.Column('pay_schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('anchor', sa.Date(), nullable=False),
    sa.Column('check_date_offset_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.property_id'], ),
    sa.PrimaryKeyConstraint('pay_schedule_id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_table('employee_payroll_profile',
    sa.Column('profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('ssn_sealed', sa.Text(), nullable=True),
    sa.Column('bank_account_sealed', sa.Text(), nullable=True),
    sa.Column('bank_routing_sealed', sa.Text(), nullable=True),
    sa.Column('tax_elections_sealed', sa.Text(), nullable=True),
    sa.Column('account_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_payroll_profile')
    op.drop_table('pay_schedule')
    # ### end Alembic commands ###
