"""pay runs

Revision ID: 664579948876
Revises: 41f376721261
Create Date: 2026-07-15 23:28:47.187033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664579948876'
down_revision: Union[str, Sequence[str], None] = '41f376721261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_run',
    sa.Column('pay_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_run_id', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.property_id'], ),
    sa.PrimaryKeyConstraint('pay_run_id'),
    sa.UniqueConstraint('property_id', 'period_start')
    )
    op.create_table('usali_actual_labor_fact',
    sa.Column('actual_fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('employer_burden', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('pay_run_id', sa.Integer(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['pay_run_id'], ['pay_run.pay_run_id'], ),
    sa.PrimaryKeyConstraint('actual_fact_id'),
    sa.UniqueConstraint('pay_run_id', 'department_id')
    )
    op.create_table('pay_run_line',
    sa.Column('line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pay_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross', sa.Text(), nullable=False),
    sa.Column('employee_taxes', sa.Text(), nullable=False),
    sa.Column('employer_taxes', sa.Text(), nullable=False),
    sa.Column('net', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['pay_run_id'], ['pay_run.pay_run_id'], ),
    sa.PrimaryKeyConstraint('line_id'),
    sa.UniqueConstraint('pay_run_id', 'employee_id')
    )
    op.create_table('provider_employee_ref',
    sa.Column('ref_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_employee_id', sa.String(length=100), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('ref_id'),
    sa.UniqueConstraint('employee_id', 'provider')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_employee_ref')
    op.drop_table('pay_run_line')
    op.drop_table('usali_actual_labor_fact')
    op.drop_table('pay_run')
    # ### end Alembic commands ###
