"""statistics stage and fact tables

Revision ID: 807b8ec40dd0
Revises: 91949341b448
Create Date: 2026-07-10 08:10:16.366462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807b8ec40dd0'
down_revision: Union[str, Sequence[str], None] = '91949341b448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pms_daily_statistic_stage',
    sa.Column('stat_stage_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('pms_source', sa.String(length=20), nullable=False),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('metric_label', sa.String(length=200), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('is_prior_year', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('ingest_batch_id', sa.BigInteger(), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batch.batch_id'], ),
    sa.PrimaryKeyConstraint('stat_stage_id'),
    sa.UniqueConstraint('pms_source', 'business_date', 'row_hash')
    )
    op.create_table('usali_statistic_fact',
    sa.Column('stat_fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('pms_source', sa.String(length=20), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('metric_code', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('is_prior_year', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ingest_batch_id', sa.BigInteger(), nullable=False),
    sa.Column('stat_stage_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batch.batch_id'], ),
    sa.ForeignKeyConstraint(['stat_stage_id'], ['pms_daily_statistic_stage.stat_stage_id'], ),
    sa.PrimaryKeyConstraint('stat_fact_id'),
    sa.UniqueConstraint('stat_stage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usali_statistic_fact')
    op.drop_table('pms_daily_statistic_stage')
    # ### end Alembic commands ###
