"""initial schema

Revision ID: 89d814b91116
Revises: 
Create Date: 2026-07-08 21:50:06.978656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d814b91116'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_batch',
    sa.Column('batch_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pms_source', sa.String(length=20), nullable=False),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('usali_mapping_dictionary',
    sa.Column('mapping_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pms_source', sa.String(length=20), nullable=False),
    sa.Column('pms_trx_code', sa.String(length=50), nullable=False),
    sa.Column('usali_edition', sa.Integer(), nullable=False),
    sa.Column('usali_schedule_id', sa.Integer(), nullable=True),
    sa.Column('usali_major_category', sa.String(length=100), nullable=False),
    sa.Column('usali_sub_category', sa.String(length=100), nullable=False),
    sa.Column('usali_line_item', sa.String(length=100), nullable=False),
    sa.Column('gl_account_code', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('mapping_id'),
    sa.UniqueConstraint('pms_source', 'pms_trx_code', 'usali_edition')
    )
    op.create_table('usali_schedule',
    sa.Column('usali_edition', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('usali_edition', 'schedule_id')
    )
    op.create_table('mapping_exception',
    sa.Column('exception_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pms_source', sa.String(length=20), nullable=False),
    sa.Column('pms_trx_code', sa.String(length=50), nullable=False),
    sa.Column('pms_trx_desc', sa.String(length=255), nullable=True),
    sa.Column('raw_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('ingest_batch_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batch.batch_id'], ),
    sa.PrimaryKeyConstraint('exception_id')
    )
    op.create_table('pms_daily_financial_stage',
    sa.Column('stage_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('pms_source', sa.String(length=20), nullable=False),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('pms_trx_code', sa.String(length=50), nullable=False),
    sa.Column('pms_trx_desc', sa.String(length=255), nullable=True),
    sa.Column('raw_amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=30), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('ingest_batch_id', sa.BigInteger(), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batch.batch_id'], ),
    sa.PrimaryKeyConstraint('stage_id'),
    sa.UniqueConstraint('pms_source', 'business_date', 'row_hash')
    )
    op.create_table('usali_financial_fact',
    sa.Column('fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('pms_source', sa.String(length=20), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('usali_edition', sa.Integer(), nullable=False),
    sa.Column('usali_schedule_id', sa.Integer(), nullable=True),
    sa.Column('usali_major_category', sa.String(length=100), nullable=False),
    sa.Column('usali_sub_category', sa.String(length=100), nullable=False),
    sa.Column('usali_line_item', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('gl_account_code', sa.String(length=50), nullable=True),
    sa.Column('ingest_batch_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batch.batch_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['pms_daily_financial_stage.stage_id'], ),
    sa.PrimaryKeyConstraint('fact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usali_financial_fact')
    op.drop_table('pms_daily_financial_stage')
    op.drop_table('mapping_exception')
    op.drop_table('usali_schedule')
    op.drop_table('usali_mapping_dictionary')
    op.drop_table('ingest_batch')
    # ### end Alembic commands ###
