"""track stage_id on outputs

Revision ID: 91949341b448
Revises: 89d814b91116
Create Date: 2026-07-09 22:15:57.911826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91949341b448'
down_revision: Union[str, Sequence[str], None] = '89d814b91116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adds NOT NULL `mapping_exception.stage_id` with no backfill: exception rows
    created before this revision have no recoverable stage_id, so the upgrade
    refuses to run while any exist rather than dying on a NotNullViolation.
    Resolve or archive those rows first (they are unmapped-code diagnostics;
    re-running `transform` after this upgrade regenerates them with stage_ids).
    """
    legacy = op.get_bind().execute(
        sa.text("SELECT COUNT(*) FROM mapping_exception")
    ).scalar()
    if legacy:
        raise RuntimeError(
            f"mapping_exception has {legacy} pre-existing row(s) that predate stage_id "
            "tracking and cannot be backfilled. Archive or delete them (e.g. "
            "`DELETE FROM mapping_exception`) and re-run the upgrade; re-running "
            "`usali transform` afterwards will regenerate them with stage_ids."
        )
    op.add_column('mapping_exception', sa.Column('stage_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint('uq_mapping_exception_stage_id', 'mapping_exception', ['stage_id'])
    op.create_foreign_key(
        'fk_mapping_exception_stage_id_pms_daily_financial_stage',
        'mapping_exception',
        'pms_daily_financial_stage',
        ['stage_id'],
        ['stage_id'],
    )
    op.create_unique_constraint('uq_usali_financial_fact_stage_id', 'usali_financial_fact', ['stage_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usali_financial_fact_stage_id', 'usali_financial_fact', type_='unique')
    op.drop_constraint(
        'fk_mapping_exception_stage_id_pms_daily_financial_stage', 'mapping_exception', type_='foreignkey'
    )
    op.drop_constraint('uq_mapping_exception_stage_id', 'mapping_exception', type_='unique')
    op.drop_column('mapping_exception', 'stage_id')
    # ### end Alembic commands ###
