"""usali labor fact

Revision ID: a2d2d34af34e
Revises: 712ad594aeb3
Create Date: 2026-07-14 21:50:01.399105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d2d34af34e'
down_revision: Union[str, Sequence[str], None] = '712ad594aeb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usali_labor_fact',
    sa.Column('labor_fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ot_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('est_cost', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('timecard_id', sa.Integer(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['timecard_id'], ['timecard.timecard_id'], ),
    sa.PrimaryKeyConstraint('labor_fact_id'),
    sa.UniqueConstraint('property_id', 'business_date', 'department_id', 'timecard_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usali_labor_fact')
    # ### end Alembic commands ###
