"""segmentation stage and fact tables

Revision ID: ca7362bc3650
Revises: 807b8ec40dd0
Create Date: 2026-07-10 09:05:27.180016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7362bc3650'
down_revision: Union[str, Sequence[str], None] = '807b8ec40dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pms_daily_segment_stage',
    sa.Column('segment_stage_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('pms_source', sa.String(length=20), nullable=False),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('segment_code', sa.String(length=50), nullable=False),
    sa.Column('segment_desc', sa.String(length=200), nullable=True),
    sa.Column('measure', sa.String(length=30), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('ingest_batch_id', sa.BigInteger(), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batch.batch_id'], ),
    sa.PrimaryKeyConstraint('segment_stage_id'),
    sa.UniqueConstraint('pms_source', 'business_date', 'row_hash')
    )
    op.create_table('usali_segment_fact',
    sa.Column('segment_fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('pms_source', sa.String(length=20), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('usali_segment', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('rooms', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('room_revenue', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('ingest_batch_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batch.batch_id'], ),
    sa.PrimaryKeyConstraint('segment_fact_id'),
    sa.UniqueConstraint('pms_source', 'property_id', 'business_date', 'usali_segment', 'period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usali_segment_fact')
    op.drop_table('pms_daily_segment_stage')
    # ### end Alembic commands ###
