"""Render the synthetic Opera sample's first page for the marketing site.

The marketing homepage shows an unreadable trial balance turning into an
operating statement. The "before" image is the SAME synthetic report the /try
preview offers as "an Opera trial balance"
(frontend/src/pages/PreviewPage.tsx, fetched at
/samples/opera-trial-balance-sample.pdf) -- generated by
gen_preview_samples.py and committed at frontend/public/samples/. Real exports
under ~/Desktop/Sample Hotel carry production figures and must never be read,
copied, or rendered by this script.

Run: uv run python scripts/gen_marketing_assets.py
"""

from __future__ import annotations

from pathlib import Path

import pypdfium2 as pdfium
from PIL import Image, ImageDraw, ImageFont, ImageOps

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "frontend/public/samples/opera-trial-balance-sample.pdf"
TARGET = REPO / "marketing/public/before-trial-balance.webp"
SCALE = 2.0
CROP_MARGIN = 24  # px at SCALE=2.0


def _crop_to_content(image: Image.Image, margin: int) -> Image.Image:
    """Crop a white-background page render down to its printed content.

    The rendered PDF page is mostly blank below the report's last line;
    `Image.getbbox()` finds the bounding box of non-zero pixels, but a white
    background has no zero pixels, so the grayscale render is inverted first
    (white -> black) to make the content the non-zero region. The box is then
    expanded by `margin` on each side and clamped to the image bounds.
    """
    grayscale = image.convert("L")
    bbox = ImageOps.invert(grayscale).getbbox()
    if bbox is None:
        return image
    left, top, right, bottom = bbox
    left = max(left - margin, 0)
    top = max(top - margin, 0)
    right = min(right + margin, image.width)
    bottom = min(bottom + margin, image.height)
    return image.crop((left, top, right, bottom))


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(
            f"{SOURCE} is missing. Run: uv run python scripts/gen_preview_samples.py"
        )

    pdf = pdfium.PdfDocument(SOURCE)
    image = pdf[0].render(scale=SCALE).to_pil()
    before_size = image.size
    image = _crop_to_content(image, CROP_MARGIN)
    print(f"cropped {before_size} -> {image.size}")
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    image.save(TARGET, "WEBP", quality=80, method=6)
    print(f"wrote {TARGET.relative_to(REPO)} ({TARGET.stat().st_size // 1024} KB)")


def og_card() -> None:
    """The social card, drawn in code so it can be regenerated rather than
    re-exported from a design tool by hand.

    The three colors below are hand-converted sRGB approximations of the oklch
    values in shared/brand.css -- PIL cannot read CSS, so they ARE a second
    copy and they CAN drift. Nothing detects that: the card is a PNG, and no
    test compares its pixels to the stylesheet. If the brand colors change,
    someone has to remember to re-run this. That is the known cost of having a
    raster social card at all.
    """
    canvas = (247, 242, 234)   # --color-brand-canvas
    ink = (51, 41, 31)         # --color-brand-ink
    accent = (189, 91, 61)     # --color-brand-accent

    image = Image.new("RGB", (1200, 630), canvas)
    draw = ImageDraw.Draw(image)

    # Georgia is confirmed present at this path on this machine (this script
    # was run on macOS to generate the committed PNG; it is not run in CI).
    # On a machine without it, substitute any serif the system has -- the
    # brand's display face (shared/brand.css --font-display) is a serif, so
    # keep it one.
    title = ImageFont.truetype("/System/Library/Fonts/Supplemental/Georgia.ttf", 68)
    body = ImageFont.truetype("/System/Library/Fonts/Supplemental/Georgia.ttf", 30)

    draw.text((80, 150), "Run the money and the labor", font=title, fill=ink)
    draw.text((80, 232), "for every property you operate.", font=title, fill=ink)
    draw.text((80, 360), "One property or one hundred.", font=body, fill=accent)
    draw.rectangle((80, 470, 200, 474), fill=accent)
    draw.text((80, 500), "Open Hospitality", font=body, fill=ink)

    target = REPO / "marketing/public/og.png"
    image.save(target, "PNG")
    print(f"wrote {target.relative_to(REPO)} ({target.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
    og_card()
