# The auth-service image (K3): the OFFICIAL Keycloak image plus exactly
# one file — the CLOUD realm generated by make_cloud_realm.py (dev
# credentials stripped, client secrets ROTATED-AT-DEPLOY, public
# hostnames only). The Cloud SQL connection is a proxy SIDECAR in the
# service spec, so no third-party jars enter this image.
#
# Built by deploy_auth.sh from a temp context that holds only this file
# and the generated realm.
FROM quay.io/keycloak/keycloak:26.0
ENV KC_DB=postgres
# The Open Hospitality login theme (pine & brass) — a CSS skin over the
# stock login theme. Baked in so the realm's loginTheme=open-hospitality
# resolves; the realm attribute itself is set post-deploy (configure_auth).
COPY open-hospitality /opt/keycloak/themes/open-hospitality
RUN /opt/keycloak/bin/kc.sh build --db=postgres
COPY realm-usali-cloud.json /opt/keycloak/data/import/realm-usali-cloud.json
# --import-realm is first-boot-only in effect: an existing realm in the
# database is left untouched on every later cold start.
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized", "--import-realm"]
