/// <reference types="node" />
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  Aes256Gcm,
  CipherSuite,
  DhkemP256HkdfSha256,
  HkdfSha256,
} from '@hpke/core'
import { describe, expect, it } from 'vitest'

// The crux of C1, JS side: prove @hpke/core round-trips the SAME committed
// fixture that pyhpke opens in tests/test_hpke_interop.py. This guards against a
// future @hpke/core upgrade silently changing the suite/info/aad/point encoding
// out from under the server. The fixture is generated by
// frontend/scripts/gen_hpke_fixture.mjs and lives at the repo root tests/.
const here = dirname(fileURLToPath(import.meta.url))
const fixture = JSON.parse(
  readFileSync(join(here, '..', '..', '..', 'tests', 'fixtures', 'hpke_interop.json'), 'utf8'),
) as {
  private_key_raw_b64: string
  public_key_sec1_b64: string
  plaintext: string
  aad: string
  info: string
  envelope: { version: number; suite: string; key_id: string; enc: string; ct: string }
}

const SUITE_LABEL = 'DHKEM-P256-HKDF-SHA256/HKDF-SHA256/AES-256-GCM'

const b64ToBytes = (b64: string): Uint8Array =>
  Uint8Array.from(atob(b64), (c) => c.charCodeAt(0))
// @hpke/core's kem.importKey wants a true ArrayBuffer (not a view); build one.
const b64ToArrayBuffer = (b64: string): ArrayBuffer => {
  const bytes = b64ToBytes(b64)
  const buf = new ArrayBuffer(bytes.byteLength)
  new Uint8Array(buf).set(bytes)
  return buf
}
const bytesToB64 = (u8: Uint8Array): string => btoa(String.fromCharCode(...u8))
const utf8 = (s: string): Uint8Array => new TextEncoder().encode(s)

function newSuite(): CipherSuite {
  return new CipherSuite({
    kem: new DhkemP256HkdfSha256(),
    kdf: new HkdfSha256(),
    aead: new Aes256Gcm(),
  })
}

describe('HPKE cross-library interop (committed fixture)', () => {
  it('pins the exact wire contract the server expects', () => {
    expect(fixture.envelope.suite).toBe(SUITE_LABEL)
    expect(fixture.info).toBe('usali-payroll-pii/v1')
    expect(fixture.aad).toBe('7:ssn')
    // enc and the recipient public key are both 65-byte SEC1 uncompressed points.
    expect(b64ToBytes(fixture.envelope.enc).byteLength).toBe(65)
    expect(b64ToBytes(fixture.envelope.enc)[0]).toBe(0x04)
    expect(b64ToBytes(fixture.public_key_sec1_b64).byteLength).toBe(65)
  })

  it('@hpke/core opens the committed envelope with the fixed private key', async () => {
    const suite = newSuite()
    // @hpke/core imports the recipient private key as a raw 32-byte scalar.
    const recipientKey = await suite.kem.importKey(
      'raw',
      b64ToArrayBuffer(fixture.private_key_raw_b64),
      false,
    )
    const recip = await suite.createRecipientContext({
      recipientKey,
      enc: b64ToBytes(fixture.envelope.enc),
      info: utf8(fixture.info),
    })
    const pt = await recip.open(b64ToBytes(fixture.envelope.ct), utf8(fixture.aad))
    expect(new TextDecoder().decode(pt)).toBe(fixture.plaintext)
  })

  it('@hpke/core seals to the fixed public key and re-opens (self round-trip)', async () => {
    const suite = newSuite()
    const recipientPublicKey = await suite.kem.importKey(
      'raw',
      b64ToArrayBuffer(fixture.public_key_sec1_b64),
      true,
    )
    const sender = await suite.createSenderContext({
      recipientPublicKey,
      info: utf8(fixture.info),
    })
    const ct = await sender.seal(utf8(fixture.plaintext), utf8(fixture.aad))

    // The freshly sealed envelope has the same shape the server validates:
    // a 65-byte SEC1 enc point and the identical suite label.
    const enc = new Uint8Array(sender.enc)
    expect(enc.byteLength).toBe(65)
    expect(bytesToB64(enc)).toHaveLength(88) // 65 bytes -> 88 b64 chars

    const recipientKey = await suite.kem.importKey(
      'raw',
      b64ToArrayBuffer(fixture.private_key_raw_b64),
      false,
    )
    const recip = await suite.createRecipientContext({
      recipientKey,
      enc: sender.enc,
      info: utf8(fixture.info),
    })
    const pt = await recip.open(ct, utf8(fixture.aad))
    expect(new TextDecoder().decode(pt)).toBe(fixture.plaintext)
  })

  it('opening under a different AAD fails (field-binding is enforced)', async () => {
    const suite = newSuite()
    const recipientKey = await suite.kem.importKey(
      'raw',
      b64ToArrayBuffer(fixture.private_key_raw_b64),
      false,
    )
    const recip = await suite.createRecipientContext({
      recipientKey,
      enc: b64ToBytes(fixture.envelope.enc),
      info: utf8(fixture.info),
    })
    await expect(
      recip.open(b64ToBytes(fixture.envelope.ct), utf8('7:bank_account')),
    ).rejects.toThrow()
  })
})
